### PR TITLE
fix(env): Fix sample env file to correctly work with MySQL

### PR DESCRIPTION
**Pull request by CuriousLearner**
Fix the hostname in connection url string for MySQL connection.

Also, updated an old comment to be correct :)

cc @MichaelKohler

### CODE REVIEW

**Comment by MichaelKohler** [comment]
I'm defering this to @akatsoulas. r?

**Comment by CuriousLearner** [comment]
On re-thinking about the change, I think the old connection string works with the docker setup as internally in the docker-compose file, the `db` is mapped to the container running MySQL.

There is no solution to it, other than mentioning in the docs that in one of the ways, this string needs to be changed after the `env-dist` is copied to `.env

I think we need to make this explicit in the docs if someone is setting it up the normal way.

**Comment by Mte90** [comment]
But you need to change for docker or for virtualenv?

**Comment by akatsoulas** [comment]
@CuriousLearner thank you for this PR!
This change is needed for the virtualenv and it's going to break the docker installation option. I would suggest to add this entry commented in the env-dist file and as the @CuriousLearner suggested, add an entry in the documentation to remove the comment  after copying the file. 

@CuriousLearner is this something that you are interested in working on?

**Comment by CuriousLearner** [comment]
@akatsoulas Exactly. Sure, I'll submit the changes in a while.

**Comment by CuriousLearner** [comment]
@akatsoulas Can you please check the PR now? :)

**Pull request merged**
