### PR TITLE
Feature/dashboard improvements

### PR DESCRIPTION
**Pull request by MichaelKohler**
https://bugzilla.mozilla.org/show_bug.cgi?id=1483261
https://bugzilla.mozilla.org/show_bug.cgi?id=1483263

### CODE REVIEW

**Comment by Mte90** [comment]
This will fix the access to the invite page and will help on show the application section on the dashboard?

**Comment by MichaelKohler** [comment]
> This will fix the access to the invite page and will help on show the application section on the dashboard?

Let me do the invite page as a follow up. I knew there was a reason I don't like largely scoped bugs ;)

**Comment by Mte90** [comment]
Ok because I written that is one of this tickets as I can remember

**Comment by akatsoulas** [comment]
Probably you need to rebase this PR with master.

**Pull request merged**
