### PR TITLE
[Fix bug 1139878] Change report form fields to facilitate "initiatives".

### PR DESCRIPTION
**Pull request by johngian**
* ChoiceField instead ModelMultipleChoiceField for contribution areas
* Campaign is now a required field
* Removed CSS/JS code that handled campaign show/hide

### CODE REVIEW

**Comment by johngian** [comment]
@akatsoulas Tests are now passing.

**Comment by akatsoulas** [comment]
Question: Should we remove the null=True from the reports model?

**Comment by johngian** [comment]
I think that this will break the relations for all past reports without a relation to ``Campaign``.

**Comment by comzeradd** [comment]
Nice work :coffee: 

Please rebase before merging. r+wc

**Pull request merged**
