### PR TITLE
[bug 1202653] Update geo system to use GENC list of countries and correct terminology

### PR DESCRIPTION
**Pull request by Mte90**
Check bugzilla for discussion about the implementation https://bugzilla.mozilla.org/show_bug.cgi?id=1202653

### CODE REVIEW

**Comment by Mte90** [comment]
I think that we can also implement a system to use the configured country in the Reps profile in that pr.

**Comment by MichaelKohler** [comment]
What do you mean by that?

**Comment by Mte90** [comment]
Nevermind, the issue was on my local system where I didn't configured a country -.-'

**Comment by akatsoulas** [comment]
Is this PR still relevant?

**Comment by MichaelKohler** [comment]
Yes, but WIP.

**Comment by Mte90** [comment]
I updated the builtin json but the list is not used.
Looking at the code is using product_details package for that list so I am not sure that this files are used.
I am not sure where is that library and from where is downloaded.

**Comment by Mte90** [comment]
@akatsoulas do you have hints about that problem?

**Comment by Mte90** [comment]
Another ping for @akatsoulas

**Comment by akatsoulas** [comment]
After discussing this with @Mte90 and @MichaelKohler we agreed that we will not proceed with this change.

**Pull request closed without merging**
