### PR TITLE
Kpi minor enhancements

### PR DESCRIPTION
**Pull request by comzeradd**

### CODE REVIEW

**Comment by johngian** [comment]
I suggest to use the unminified d3.js and compress it like we do with the rest of the libs.

https://github.com/mbostock/d3/releases/download/v3.5.5/d3.zip

**Comment by comzeradd** [comment]
Thanks @johngian. PR updated.

**Comment by johngian** [comment]
* Please move this fix to another commit: https://github.com/comzeradd/remo/commit/592eea9cb8bd69dfb70e8493df78d6e9647a9932#diff-8883a863906ee9ab9e6b8f44d4ad13e1R413

* You can squash the minor fixes to a single commit but this is just a suggestion (feel free to choose)

* I' we pushed some changes here: https://github.com/johngian/remo/tree/pr-998
 * Feel free to cherry pick the jshint fixes
 * I am not sure if the second fix is required. Please r? and apply if we want to enable multiple filters.

**Comment by johngian** [comment]
r+wc

**Comment by comzeradd** [comment]
Thanks. Squashed and Cherry-picked :gift:

**Pull request merged**
