### PR TITLE
[fix bug 994736] The website now provides a 'hamburger button' in respon...

### PR DESCRIPTION
**Pull request by TheTeraByte**
...sive view that on being clicked shows the full navigation.

### CODE REVIEW

**Comment by TheTeraByte** [comment]
Just saw this comment! I will make the suggested changes within a couple of days :) Thanks for the feedback!

**Comment by TheTeraByte** [comment]
@wraybowling I made the menu be hidden by default however, was having slight difficulties putting the hamburger button inside #logo-box. When I do so it starts appearing in all views (i.e. not just in responsive design view). I was wondering whether Django has any conditionals that allow me to show it only in mobile view? Or if there's an alternate CSS way of achieving the same layout :)

**Comment by akatsoulas** [comment]
@comzeradd maybe you can continue this?

**Comment by johngian** [comment]
Hey @TheTeraByte 
I am closing this PR due to inactivity. You can always reopen this if there is any progress or reach out to us for an other ``good first bug``.

Thank you for the contribution :rocket:

**Pull request closed without merging**
