### PR TITLE
Remove playdoh and add peep.

### PR DESCRIPTION
**Pull request by akatsoulas**

### CODE REVIEW

**Comment by johngian** [comment]
Please add ``python-memcached`` in requirements.

**Comment by akatsoulas** [comment]
@johngian updated.

**Comment by johngian** [comment]
It looks like there are some missing dependencies in ``prod.txt``:

```
Installing collected packages: ipaddress, fake-factory, rcssmin, rjsmin
Successfully installed fake-factory-0.5.7 ipaddress-1.0.16 rcssmin-1.0.6 rjsmin-1.0.12
```

**Comment by johngian** [comment]
Same for prod (with some overlaps because dev inherits prod) :
```
Successfully built rcssmin rjsmin tornado PyYAML argh watchdog pathtools simplegeneric pexpect backports.ssl-match-hostname
Installing collected packages: rcssmin, rjsmin, babel, snowballstemmer, imagesize, alabaster, backports.ssl-match-hostname, singledispatch, certifi, backports-abc, tornado, PyYAML, argh, pathtools, watchdog, livereload, mccabe, pyflakes, decorator, ipython-genutils, traitlets, pathlib2, pickleshare, simplegeneric, ptyprocess, pexpect
Successfully installed PyYAML-3.11 alabaster-0.7.7 argh-0.26.1 babel-2.3.4 backports-abc-0.4 backports.ssl-match-hostname-3.5.0.1 certifi-2016.2.28 decorator-4.0.9 imagesize-0.7.1 ipython-genutils-0.1.0 livereload-2.4.1 mccabe-0.4.0 pathlib2-2.1.0 pathtools-0.1.2 pexpect-4.0.1 pickleshare-0.7.2 ptyprocess-0.5.1 pyflakes-1.0.0 rcssmin-1.0.6 rjsmin-1.0.12 simplegeneric-0.8.1 singledispatch-3.4.0.3 snowballstemmer-1.2.1 tornado-4.3 traitlets-4.2.1 watchdog-0.8.3
```

**Comment by johngian** [comment]
r+wc

**Comment by akatsoulas** [comment]
thanks!

**Pull request merged**
