### PR TITLE
[bug 1139878] Change the size of textarea in reports description.

### PR DESCRIPTION
**Pull request by akatsoulas**

### CODE REVIEW

**Comment by akatsoulas** [comment]
@johngian r?

**Comment by johngian** [comment]
LGTM r+

**Comment by akatsoulas** [comment]
@johngian I also added a pictogram to the initiatives. I chose the `medal` so that we can have the same pictograms in both events and reports for these fields (the events pictograms are added in pr #948)

**Comment by johngian** [comment]
Pictogram looks good. r+

**Pull request merged**
