### PR TITLE
Update documentation for Django 1.8.

### PR DESCRIPTION
**Pull request by akatsoulas**
@johngian r?

### CODE REVIEW

**Comment by akatsoulas** [comment]
@johngian can you have a quick pass?

**Comment by johngian** [comment]
I am getting this errors when building locally:
```
reading sources... [100%] static                                                                                                                                                                                     
mozilla/remo/docs/installation-virtualenv.rst:28: ERROR: Unknown target name: "fork the main remo repository".
mozilla/remo/docs/installation-virtualenv.rst:111: ERROR: Unknown target name: "mysql site".
```

**Comment by akatsoulas** [comment]
@johngian pr updated

**Comment by johngian** [comment]
r+

**Pull request merged**
