### PR TITLE
Upgrade browserid to version 0.11

### PR DESCRIPTION
**Pull request by akatsoulas**

### CODE REVIEW

**Comment by akatsoulas** [comment]
The last two commits will be squashed into one after the review.

**Comment by akatsoulas** [comment]
@glogiotatidis maybe you can r this?

**Comment by glogiotatidis** [comment]
Tests fail here, can you please check @akatsoulas ?

**Comment by akatsoulas** [comment]
@glogiotatidis ready sir for your review :)

**Comment by glogiotatidis** [comment]
code wise looks ok and did simple testing and works as expected. I didn't dive deep into this but given that this is mostly code moving around you should be good to go. r+

**Pull request merged**
