### PR TITLE
Add Redis dependency

### PR DESCRIPTION
**Pull request by flamingspaz**

### CODE REVIEW

**Comment by johngian** [comment]
I am not sure if these are the correct dependencies:

```
$ pip install celery[redis]==3.1.23
```

returns:

```
Successfully installed billiard-3.3.0.23 kombu-3.0.37 redis-2.10.5
```

**Comment by akatsoulas** [comment]
Kombu and blliard are already in the requirements.

**Comment by johngian** [comment]
@akatsoulas it looks like our dependencies are not exactly right. From current master with fresh docker build.

```
$ pip install celery==3.1.23
...
...
...
Successfully installed billiard-3.3.0.23 kombu-3.0.37
```

**Comment by johngian** [comment]
The PR might work with the current dependencies but its probably better to upgrade @akatsoulas what do you think?

**Comment by akatsoulas** [comment]
let's do it! @flamingspaz feel free to merge with the upgrades included

**Pull request merged**
