### PR TITLE
Increase visibility timeout to 7 days.

### PR DESCRIPTION
**Pull request by akatsoulas**
@flamingspaz r?

This poll [0] was active for 5 days so I increased the limit to 7. Let's see if that helps.

[0] https://reps.mozilla.org/v/budget-request-flore-allemandou-https-reps-mozilla-org-e-write-the-docs/

### CODE REVIEW

**Comment by akatsoulas** [comment]
@flamingspaz If you are happy with this PR, feel free to merge.

**Comment by flamingspaz** [comment]
Is there any reason we couldn't set it to 28 days?

**Comment by akatsoulas** [comment]
Other than it feels too big, none

**Comment by flamingspaz** [comment]
Lets do 7 for now then, I'm not sure if this is even working correctly as tasks are still being repushed every hour.

**Pull request merged**
